# Generated by Django 2.0.1 on 2018-04-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_basicdetails_annual_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='DOB',
            field=models.DateField(default=None),
        ),
    ]
