# Generated by Django 2.0.1 on 2018-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_basicdetails_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='user_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
