# Generated by Django 2.0.1 on 2018-04-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_presentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentlocation',
            name='user_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
