# Generated by Django 2.0.1 on 2018-04-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_moneytransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='account_number',
            new_name='enter_the_amount_to_be_transferred_in_INR',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='balance',
            new_name='enter_the_destination_account_number',
        ),
    ]
