# Generated by Django 2.0.1 on 2018-04-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20180422_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='enter_your_account_number',
            field=models.IntegerField(default=None),
        ),
    ]
