# Generated by Django 2.0.1 on 2018-04-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_moneytransfer_enter_your_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneytransfer',
            name='enter_your_account_number',
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='enter_your_user_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
